import { Inter } from "next/font/google";
import "./globals.css";
import Sessionwrapper from "./Component/Sessionwrapper";
import { TaskProvider } from "./context/TaskContext";
import DarkModeToggle from "./Component/DarkModeToggle"; // Import DarkModeToggle

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}bg-gray-100 dark:bg-gray-900 text-black dark:text-white`}>
        <Sessionwrapper>
          <TaskProvider>
            <DarkModeToggle /> {/* Include DarkModeToggle */}
            {children}
          </TaskProvider>
        </Sessionwrapper>
      </body>
    </html>
  );
}
